networks:
  default: development
  development:
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 12000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      #      fork: https://localhost:9545
      fork: https://goerli.infura.io/v3/8487bbcc35f94f4c92187606125f3d60